POST http://localhost:3000/users/ HTTP/1.1
Content-Type: application/json

{
    "firstName": "Romana",
    "lastName":"Rotsman",
    "email":"romana@gmail.com",
    "password":"odf@hk", 
    "birthday":"1974-04-21",
    "isMale" : false
    }
 