POST http://localhost:3000/users/ HTTP/1.1
Content-Type: application/json

{
    "firstName": "Annabella",
    "lastName":"Ranamas",
    "email":"ramariasa@gmail.com",
    "password":"odf@ ml1hk", 
    "birthday":"1978-04-01",
    "isMale" : false
    }
 