POST http://localhost:3000/users/ HTTP/1.1
Content-Type: application/json

{
    "firstName": "Mariana",
    "lastName":"Pit",
    "email":"marpit@gmail.com",
    "password":" mnyuoiuhk", 
    "birthday":"1974-08-22",
    "isMale" : false
    }
 