POST http://localhost:3000/users/ HTTP/1.1
Content-Type: application/json

{
    "firstName": "",
    "lastName":"Silva",
    "email":"sa@gmail.com",
    "password":" seilva@01", 
    "birthday":"1968-04-17",
    "isMale" : false
    }
 