POST http://localhost:3000/users/ HTTP/1.1
Content-Type: application/json

{
    "firstName": "Brad",
    "lastName":"Kolpenesa",
    "email":"kolpbrsaad@gmail.com",
    "password":" jkbrakold@01", 
    "birthday":"1972-01-27",
    "isMale" : true
    }
 